export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const UNSET_LOGGED_IN = "UNSET_LOGGED_IN";
export const SET_MESSAGE = "SET_MESSAGE";
export const UNSET_MESSAGE = "UNSET_MESSAGE";
export const SET_AUTH_USER = "SET_AUTH_USER";
export const UNSET_AUTH_USER = "UNSET_AUTH_USER";

//------------ Table Name Userinfo  -------------
export const USERINFO_UNSET_ALL_STATE = "USERINFO_UNSET_ALL_STATE";
export const USERINFO_SET_MSG = "USERINFO_SET_MSG";
export const USERINFO_UNSET_MSG = "USERINFO_UNSET_MSG";
export const USERINFO_SET_SCHEMA = "USERINFO_SET_SCHEMA";
export const USERINFO_UNSET_SCHEMA = "USERINFO_UNSET_SCHEMA";
export const USERINFO_SET_ACTION_PROCESS = "USERINFO_SET_ACTION_PROCESS";
export const USERINFO_UNSET_ACTION_PROCESS = "USERINFO_UNSET_ACTION_PROCESS";
export const USERINFO_SET_LIST_DATA = "USERINFO_SET_LIST_DATA";
export const USERINFO_UNSET_LIST_DATA = "USERINFO_UNSET_LIST_DATA";
export const USERINFO_SET_ACTION_STATUS = "USERINFO_SET_ACTION_STATUS";
export const USERINFO_UNSET_ACTION_STATUS = "USERINFO_UNSET_ACTION_STATUS";

//------------ Table Name dessert info  -------------
export const SET_DESERTS = "SET_DESERTS";
export const UNSET_DESERTS = "UNSET_DESERTS";
export const DELETE_DESERTS_ITEM = "DELETE_DESERTS_ITEM";
export const SAVE_DESERTS_ITEM = "SAVE_DESERTS_ITEM";
export const EDIT_DESERTS_ITEM = "EDIT_DESERTS_ITEM";

